name: dev

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'src/**'
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
        cache: true
    - name: Build App
      run: |
        cd ./src
        go mod tidy
        go build -o backend-pioneer main.go
        mv backend-pioneer ../
    - name: Create .env
      run: |
        echo "DB_HOST='${{secrets.DB_HOST}}'" > .env
        echo "DB_PORT='${{secrets.DB_PORT}}'" >> .env
        echo "DB_USER='${{secrets.DB_USER}}'" >> .env
        echo "DB_PASSWORD='${{secrets.DB_PASSWORD}}'" >> .env
        echo "DB_NAME='${{secrets.DB_NAME}}'" >> .env
        
        echo "SERVER_PORT='${{vars.DEV_SERVER_PORT}}'" >> .env

        echo "JWT_SECRET='${{secrets.DEV_JWT_SECRET}}'" >> .env
        echo "ACCESS_TOKEN_TTL='${{vars.DEV_ACCESS_TOKEN_TTL}}'" >> .env
        echo "REFRESH_TOKEN_TTL='${{vars.DEV_REFRESH_TOKEN_TTL}}'" >> .env
        echo "VERIFICATION_TTL='${{vars.DEV_VERIFICATION_TTL}}'" >> .env

        echo "SMTP_HOST='${{secrets.DEV_SMTP_HOST}}'" >> .env
        echo "SMTP_PORT='${{vars.DEV_SMTP_PORT}}'" >> .env
        echo "SMTP_USER='${{secrets.DEV_SMTP_USER}}'" >> .env
        echo "SMTP_PASSWORD='${{secrets.DEV_SMTP_PASSWORD}}'" >> .env
        echo "SMTP_FROM='${{secrets.DEV_SMTP_FROM}}'" >> .env

    - name: Deploy to Server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_DEV_HOST }}
        username: ${{ secrets.SSH_DEV_USER }}
        key: ${{ secrets.SSH_DEV_KEY }}
        source: "backend-pioneer, .env"
        target: "/var/www/backend-pioneer"
    - name: Restart Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_DEV_HOST }}
        username: ${{ secrets.SSH_DEV_USER }}
        key: ${{ secrets.SSH_DEV_KEY }}
        script: |
          sudo chmod 600 .env
          chmod +x /var/www/backend-pioneer/backend-pioneer
          sudo systemctl restart backend-pioneer.service
